spring.application.name=CoreBankingSystem

#Connection Database (Postgresql)
spring.datasource.url=jdbc:postgresql://localhost:5432/banking
spring.datasource.username=postgres
spring.datasource.password=manman

#Matikan jpa karena memakai flyway
#Eksekutor operasi DB
spring.jpa.hibernate.ddl-auto=none


#JWT CONFIGURATION
# Secret Key
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Access Token Lifetime - 1 Hour (Milisecond)
jwt.expiration=3600000
# Refresh Token Lifetime 7 Days (Milisecond)
jwt.refresh-expiration=604800000

#DB Migration Configuration (Eksekutor DB Structure)
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=false
# Pastiin lokasinya bener (biasanya default, tapi buat jaga-jaga)
spring.flyway.locations=classpath:db/migration
