spring.application.name=CoreBankingSystem

#Connection Database (Postgresql)
spring.datasource.url=jdbc:postgresql://localhost:5432/banking
spring.datasource.username=postgres
spring.datasource.password=manman
spring.jpa.hibernate.ddl-auto=validate

#JWT CONFIGURATION

# Secret Key
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

# Access Token Lifetime - 1 Hour (Milisecond)
jwt.expiration=3600000

# Refresh Token Lifetime 7 Days (Milisecond)
jwt.refresh-expiration=604800000

